Now building but failing to install into emulator due to the following error
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install C:\Users\Linval\personalProjects\flutter_app\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1558020856.tmp/base.apk (at Binary XML file line #166): com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on sdk gphone64 x86 64